apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx-container
        image: kapilrajhybrid/nginx:v1  # Replace with your image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  labels:
    app: mynginx
spec:
  type: NodePort
  selector:
    app: mynginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012
