name: Nginx Build CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     
     - name: Build the Nginx Docker image
       run: |
         docker build . -t kapilrajhybrid/nginx:latest
         
     - name: Publish image to Docker Hub 
       run: |
         docker login -u kapilrajhybrid -p ${{ secrets.DOCKER_HUB_TOKEN }}
         docker push kapilrajhybrid/nginx:latest
        
