name: Nginx Build CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
     - uses: actions/checkout@v1
     - name: Build the Nginx Docker image
       run: |
         docker build . -t Dockerfile --tag myNginx:latest
     - name: Publish image to Docker Hub 
       run: |
         docker login -u kapilrajhybrid -p ${{ secrets.DOCKER_HUB_TOKEN }}
         docker push kapilrajhybrid/myNginx:latest
        
